language: python
dist: xenial

python:
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.9-dev"

install:
    - pip install --upgrade setuptools coveralls

script:
    - coverage run --branch --include="network_finder/*" setup.py test

after_success:
    - coveralls

notifications:
    email: false
