language: python
dist: xenial

python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"
    - "pypy2.7-6.0"
    - "pypy3.5-6.0"

install:
    - pip install --upgrade setuptools coveralls

script:
    - coverage run --branch --include="network_finder/*" setup.py test

after_success:
    - coveralls

notifications:
    email: false
