name: Python package

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9.0, 3.10.0-rc.1]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade coverage flake8
    - name: Run tests
      run: |
        coverage run --include "network_finder/*.py" -m unittest
    - name: Check coverage
      run: |
        coverage report --show-missing --fail-under=99.0
    - name: Lint with flake8
      run: |
        flake8 .
    - name: Check formatting with black
      if: "matrix.python-version == '3.6'"
      run: |
        pip install -U black
        black --check .
    - name: Build packages
      if: "matrix.python-version == '3.6'"
      run: |
        pip install -U twine wheel
        python setup.py sdist bdist_wheel
        twine check dist/*
    - name: Upload packages
      if: "matrix.python-version == '3.6'"
      uses: actions/upload-artifact@v2
      with:
        name: network-finder
        path: dist/*
